services:
  mysql_db:
    image: mysql
    restart: always
    privileged: true
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql_init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  django_backend:
    build: ./src/backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src/backend:/app
      - ./.env:/app/.env
    ports:
      - 8000:8000
    depends_on:
      mysql_db:
        condition: service_healthy
    environment:
      DATABASE_URL: mysql://root:root@mysql_db/main
    develop:
      watch:
        - path: /app
          target: /app
          action: restart

  svelte_frontend:
    build: ./src/frontend
    volumes:
      - ./src/frontend:/app
      - /app/node_modules
    ports:
      - 5173:5173
    depends_on:
      - django_backend
    environment:
      # Fixes issue with hot reloading not working through Docker
      CHOKIDAR_USEPOLLING: "true"
    develop:
      watch:
        - path: /app
          target: /app
          action: restart

volumes:
  mysql_data:
    driver: local
