# Generated by Django 4.2 on 2025-03-04 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_about_user_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialType',
            fields=[
                ('social_type', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'db_table': 'SocialType',
            },
        ),
        migrations.CreateModel(
            name='UserSocial',
            fields=[
                ('user_social_id', models.AutoField(primary_key=True, serialize=False)),
                ('social_username', models.CharField(max_length=255)),
                ('social_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.socialtype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UserSocial',
                'unique_together': {('user', 'social_type')},
            },
        ),
    ]
