# Generated by Django 4.2 on 2025-03-24 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_communitymember'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='communitymember',
            table='CommunityMember',
        ),
    ]
