# Generated by Django 4.2 on 2025-03-25 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_communitymember_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommunityMember',
        ),
    ]
