# Generated by Django 4.2 on 2025-03-26 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_post_date'),
        ('app', '0006_delete_communitymember'),
    ]

    operations = [
    ]
