# Generated by Django 4.2 on 2025-03-27 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_user_interests'),
        ('app', '0007_merge_20250326_1340'),
    ]

    operations = [
    ]
