# Generated by Django 4.2 on 2025-03-27 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_merge_0006_user_interests_0007_merge_20250326_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='interests',
        ),
    ]
