# Generated by Django 4.2 on 2025-05-02 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_event_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='program',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
