# Generated by Django 4.2 on 2025-05-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_user_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uni_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
