# Generated by Django 4.2 on 2025-05-02 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_event_max_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='community_picture',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
