# Generated by Django 4.2 on 2025-05-02 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_postlikes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('post', 'user_id')},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',     
            new_name='user',        
        ),
    ]
