# Generated by Django 4.2 on 2025-05-05 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_comment_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pending_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
