# Generated by Django 4.2 on 2025-05-05 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_user_pending_email'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set(),
        ),
    ]
