# Generated by Django 4.2 on 2025-05-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
