# Generated by Django 4.2 on 2025-05-07 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_connection'),
        ('app', '0028_populate_example_data'),
    ]

    operations = [
    ]
