name: Update Issue End Date

on:
  push:
    branches:
      - main

jobs:
  update-roadmap:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2.x

    - name: Extract issue number from commit message
      id: extract_issue_number
      run: |
        echo "ISSUE_NUMBER=$(git log -1 --pretty=%B | grep -o '#[0-9]\+' | tr -d '#')" >> $GITHUB_ENV

    - name: Get current date
      id: date
      run: echo "::set-output name=current_date::$(date -u +'%Y-%m-%dT%H:%M:%SZ')"

    - name: Update issue end date on roadmap
      if: env.ISSUE_NUMBER != ''
      uses: octokit/request-action@v2
      with:
        route: PATCH /repos/${{ github.repository }}/issues/${{ env.ISSUE_NUMBER }}
        milestone: |
          {
            "due_on": "${{ steps.date.outputs.current_date }}"
          }
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}